/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status.ui.tests;

import codeskills.designer.game.status.ui.internal.StatusActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class StatusUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StatusActivator.getInstance().getInjector("codeskills.designer.game.status.Status");
	}

}
