/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.ui.contentassist;

import codeskills.designer.game.ui.contentassist.AbstractGameProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GameProposalProvider extends AbstractGameProposalProvider {
}
