/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data.data.impl;

import codeskills.designer.data.data.ContainerResource;
import codeskills.designer.data.data.DataPackage;
import codeskills.designer.data.data.File;
import codeskills.designer.data.data.Folder;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Container Resource</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.data.data.impl.ContainerResourceImpl#getFiles <em>Files</em>}</li>
 *   <li>{@link codeskills.designer.data.data.impl.ContainerResourceImpl#getFolders <em>Folders</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ContainerResourceImpl extends ResourceImpl implements ContainerResource
{
  /**
   * The cached value of the '{@link #getFiles() <em>Files</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFiles()
   * @generated
   * @ordered
   */
  protected EList<File> files;

  /**
   * The cached value of the '{@link #getFolders() <em>Folders</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFolders()
   * @generated
   * @ordered
   */
  protected EList<Folder> folders;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContainerResourceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DataPackage.Literals.CONTAINER_RESOURCE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<File> getFiles()
  {
    if (files == null)
    {
      files = new EObjectContainmentEList<File>(File.class, this, DataPackage.CONTAINER_RESOURCE__FILES);
    }
    return files;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Folder> getFolders()
  {
    if (folders == null)
    {
      folders = new EObjectContainmentEList<Folder>(Folder.class, this, DataPackage.CONTAINER_RESOURCE__FOLDERS);
    }
    return folders;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DataPackage.CONTAINER_RESOURCE__FILES:
        return ((InternalEList<?>)getFiles()).basicRemove(otherEnd, msgs);
      case DataPackage.CONTAINER_RESOURCE__FOLDERS:
        return ((InternalEList<?>)getFolders()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DataPackage.CONTAINER_RESOURCE__FILES:
        return getFiles();
      case DataPackage.CONTAINER_RESOURCE__FOLDERS:
        return getFolders();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DataPackage.CONTAINER_RESOURCE__FILES:
        getFiles().clear();
        getFiles().addAll((Collection<? extends File>)newValue);
        return;
      case DataPackage.CONTAINER_RESOURCE__FOLDERS:
        getFolders().clear();
        getFolders().addAll((Collection<? extends Folder>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DataPackage.CONTAINER_RESOURCE__FILES:
        getFiles().clear();
        return;
      case DataPackage.CONTAINER_RESOURCE__FOLDERS:
        getFolders().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DataPackage.CONTAINER_RESOURCE__FILES:
        return files != null && !files.isEmpty();
      case DataPackage.CONTAINER_RESOURCE__FOLDERS:
        return folders != null && !folders.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ContainerResourceImpl
