/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data.data.impl;

import codeskills.designer.data.data.DataPackage;
import codeskills.designer.data.data.Folder;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Folder</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FolderImpl extends ContainerResourceImpl implements Folder
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FolderImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DataPackage.Literals.FOLDER;
  }

} //FolderImpl
