/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data.data.impl;

import codeskills.designer.data.data.DataPackage;
import codeskills.designer.data.data.Project;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Project</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ProjectImpl extends ContainerResourceImpl implements Project
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProjectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DataPackage.Literals.PROJECT;
  }

} //ProjectImpl
