/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.ui;

import codeskills.designer.game.ui.internal.GameActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GameExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GameActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GameActivator.getInstance().getInjector(GameActivator.CODESKILLS_DESIGNER_GAME_GAME);
	}
	
}
