/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.validation;

import codeskills.designer.game.validation.AbstractGameValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GameValidator extends AbstractGameValidator {
}
