/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data.data;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Container Resource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.data.data.ContainerResource#getFiles <em>Files</em>}</li>
 *   <li>{@link codeskills.designer.data.data.ContainerResource#getFolders <em>Folders</em>}</li>
 * </ul>
 *
 * @see codeskills.designer.data.data.DataPackage#getContainerResource()
 * @model
 * @generated
 */
public interface ContainerResource extends Resource
{
  /**
   * Returns the value of the '<em><b>Files</b></em>' containment reference list.
   * The list contents are of type {@link codeskills.designer.data.data.File}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Files</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Files</em>' containment reference list.
   * @see codeskills.designer.data.data.DataPackage#getContainerResource_Files()
   * @model containment="true"
   * @generated
   */
  EList<File> getFiles();

  /**
   * Returns the value of the '<em><b>Folders</b></em>' containment reference list.
   * The list contents are of type {@link codeskills.designer.data.data.Folder}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Folders</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Folders</em>' containment reference list.
   * @see codeskills.designer.data.data.DataPackage#getContainerResource_Folders()
   * @model containment="true"
   * @generated
   */
  EList<Folder> getFolders();

} // ContainerResource
