/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data.data;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>File</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.data.data.File#getExt <em>Ext</em>}</li>
 *   <li>{@link codeskills.designer.data.data.File#isChanged <em>Changed</em>}</li>
 *   <li>{@link codeskills.designer.data.data.File#getModel <em>Model</em>}</li>
 * </ul>
 *
 * @see codeskills.designer.data.data.DataPackage#getFile()
 * @model
 * @generated
 */
public interface File extends Resource
{
  /**
   * Returns the value of the '<em><b>Ext</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ext</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ext</em>' attribute.
   * @see #setExt(String)
   * @see codeskills.designer.data.data.DataPackage#getFile_Ext()
   * @model
   * @generated
   */
  String getExt();

  /**
   * Sets the value of the '{@link codeskills.designer.data.data.File#getExt <em>Ext</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ext</em>' attribute.
   * @see #getExt()
   * @generated
   */
  void setExt(String value);

  /**
   * Returns the value of the '<em><b>Changed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Changed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Changed</em>' attribute.
   * @see #setChanged(boolean)
   * @see codeskills.designer.data.data.DataPackage#getFile_Changed()
   * @model
   * @generated
   */
  boolean isChanged();

  /**
   * Sets the value of the '{@link codeskills.designer.data.data.File#isChanged <em>Changed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Changed</em>' attribute.
   * @see #isChanged()
   * @generated
   */
  void setChanged(boolean value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' reference list.
   * @see codeskills.designer.data.data.DataPackage#getFile_Model()
   * @model
   * @generated
   */
  EList<EObject> getModel();

} // File
