/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data.data;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Folder</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see codeskills.designer.data.data.DataPackage#getFolder()
 * @model
 * @generated
 */
public interface Folder extends ContainerResource
{
} // Folder
