/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.game.impl;

import codeskills.designer.game.game.GamePackage;
import codeskills.designer.game.game.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Notification</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.game.game.impl.NotificationImpl#getMessage <em>Message</em>}</li>
 *   <li>{@link codeskills.designer.game.game.impl.NotificationImpl#getIconPath <em>Icon Path</em>}</li>
 *   <li>{@link codeskills.designer.game.game.impl.NotificationImpl#getSoundPath <em>Sound Path</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NotificationImpl extends MinimalEObjectImpl.Container implements Notification
{
  /**
   * The default value of the '{@link #getMessage() <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMessage()
   * @generated
   * @ordered
   */
  protected static final String MESSAGE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMessage() <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMessage()
   * @generated
   * @ordered
   */
  protected String message = MESSAGE_EDEFAULT;

  /**
   * The default value of the '{@link #getIconPath() <em>Icon Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIconPath()
   * @generated
   * @ordered
   */
  protected static final String ICON_PATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getIconPath() <em>Icon Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIconPath()
   * @generated
   * @ordered
   */
  protected String iconPath = ICON_PATH_EDEFAULT;

  /**
   * The default value of the '{@link #getSoundPath() <em>Sound Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSoundPath()
   * @generated
   * @ordered
   */
  protected static final String SOUND_PATH_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSoundPath() <em>Sound Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSoundPath()
   * @generated
   * @ordered
   */
  protected String soundPath = SOUND_PATH_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NotificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamePackage.Literals.NOTIFICATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMessage()
  {
    return message;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMessage(String newMessage)
  {
    String oldMessage = message;
    message = newMessage;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, GamePackage.NOTIFICATION__MESSAGE, oldMessage, message));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getIconPath()
  {
    return iconPath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIconPath(String newIconPath)
  {
    String oldIconPath = iconPath;
    iconPath = newIconPath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, GamePackage.NOTIFICATION__ICON_PATH, oldIconPath, iconPath));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSoundPath()
  {
    return soundPath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSoundPath(String newSoundPath)
  {
    String oldSoundPath = soundPath;
    soundPath = newSoundPath;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, org.eclipse.emf.common.notify.Notification.SET, GamePackage.NOTIFICATION__SOUND_PATH, oldSoundPath, soundPath));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamePackage.NOTIFICATION__MESSAGE:
        return getMessage();
      case GamePackage.NOTIFICATION__ICON_PATH:
        return getIconPath();
      case GamePackage.NOTIFICATION__SOUND_PATH:
        return getSoundPath();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamePackage.NOTIFICATION__MESSAGE:
        setMessage((String)newValue);
        return;
      case GamePackage.NOTIFICATION__ICON_PATH:
        setIconPath((String)newValue);
        return;
      case GamePackage.NOTIFICATION__SOUND_PATH:
        setSoundPath((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.NOTIFICATION__MESSAGE:
        setMessage(MESSAGE_EDEFAULT);
        return;
      case GamePackage.NOTIFICATION__ICON_PATH:
        setIconPath(ICON_PATH_EDEFAULT);
        return;
      case GamePackage.NOTIFICATION__SOUND_PATH:
        setSoundPath(SOUND_PATH_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamePackage.NOTIFICATION__MESSAGE:
        return MESSAGE_EDEFAULT == null ? message != null : !MESSAGE_EDEFAULT.equals(message);
      case GamePackage.NOTIFICATION__ICON_PATH:
        return ICON_PATH_EDEFAULT == null ? iconPath != null : !ICON_PATH_EDEFAULT.equals(iconPath);
      case GamePackage.NOTIFICATION__SOUND_PATH:
        return SOUND_PATH_EDEFAULT == null ? soundPath != null : !SOUND_PATH_EDEFAULT.equals(soundPath);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (message: ");
    result.append(message);
    result.append(", iconPath: ");
    result.append(iconPath);
    result.append(", soundPath: ");
    result.append(soundPath);
    result.append(')');
    return result.toString();
  }

} //NotificationImpl
