/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class StatusRuntimeModule extends AbstractStatusRuntimeModule {
}
