/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class StatusStandaloneSetup extends StatusStandaloneSetupGenerated {

	def static void doSetup() {
		new StatusStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
