/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data.ui.contentassist;

import codeskills.designer.data.ui.contentassist.AbstractDataProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DataProposalProvider extends AbstractDataProposalProvider {
}
