/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GameRuntimeModule extends AbstractGameRuntimeModule {
}
