/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractStatusScopeProvider extends DelegatingScopeProvider {
}
