/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status;

import codeskills.designer.game.status.StatusStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class StatusStandaloneSetup extends StatusStandaloneSetupGenerated {
  public static void doSetup() {
    StatusStandaloneSetup _statusStandaloneSetup = new StatusStandaloneSetup();
    _statusStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
