/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status;

import codeskills.designer.game.status.AbstractStatusRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class StatusRuntimeModule extends AbstractStatusRuntimeModule {
}
