/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game;

import codeskills.designer.game.GameStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GameStandaloneSetup extends GameStandaloneSetupGenerated {
  public static void doSetup() {
    GameStandaloneSetup _gameStandaloneSetup = new GameStandaloneSetup();
    _gameStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
