/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data.validation;

import codeskills.designer.data.validation.AbstractDataValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DataValidator extends AbstractDataValidator {
}
