/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data;

import codeskills.designer.data.AbstractDataRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DataRuntimeModule extends AbstractDataRuntimeModule {
}
