/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data;

import codeskills.designer.data.DataStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DataStandaloneSetup extends DataStandaloneSetupGenerated {
  public static void doSetup() {
    DataStandaloneSetup _dataStandaloneSetup = new DataStandaloneSetup();
    _dataStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
