/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data.ui;

import codeskills.designer.data.ui.AbstractDataUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DataUiModule extends AbstractDataUiModule {
  public DataUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
