/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.ui.tests;

import codeskills.designer.game.ui.internal.GameActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class GameUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GameActivator.getInstance().getInjector("codeskills.designer.game.Game");
	}

}
