/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StatusAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("codeskills/designer/game/status/parser/antlr/internal/InternalStatus.tokens");
	}
}
