/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.scoping;

import codeskills.designer.game.scoping.AbstractGameScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GameScopeProvider extends AbstractGameScopeProvider {
}
