/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status.status.impl;

import codeskills.designer.game.game.Group;

import codeskills.designer.game.status.status.AchievementS;
import codeskills.designer.game.status.status.GroupS;
import codeskills.designer.game.status.status.StatusPackage;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Group S</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.game.status.status.impl.GroupSImpl#getGroup <em>Group</em>}</li>
 *   <li>{@link codeskills.designer.game.status.status.impl.GroupSImpl#getAchievements <em>Achievements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GroupSImpl extends SImpl implements GroupS
{
  /**
   * The cached value of the '{@link #getGroup() <em>Group</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGroup()
   * @generated
   * @ordered
   */
  protected Group group;

  /**
   * The cached value of the '{@link #getAchievements() <em>Achievements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAchievements()
   * @generated
   * @ordered
   */
  protected EList<AchievementS> achievements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GroupSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StatusPackage.Literals.GROUP_S;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Group getGroup()
  {
    if (group != null && group.eIsProxy())
    {
      InternalEObject oldGroup = (InternalEObject)group;
      group = (Group)eResolveProxy(oldGroup);
      if (group != oldGroup)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, StatusPackage.GROUP_S__GROUP, oldGroup, group));
      }
    }
    return group;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Group basicGetGroup()
  {
    return group;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setGroup(Group newGroup)
  {
    Group oldGroup = group;
    group = newGroup;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, StatusPackage.GROUP_S__GROUP, oldGroup, group));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<AchievementS> getAchievements()
  {
    if (achievements == null)
    {
      achievements = new EObjectContainmentEList<AchievementS>(AchievementS.class, this, StatusPackage.GROUP_S__ACHIEVEMENTS);
    }
    return achievements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case StatusPackage.GROUP_S__ACHIEVEMENTS:
        return ((InternalEList<?>)getAchievements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case StatusPackage.GROUP_S__GROUP:
        if (resolve) return getGroup();
        return basicGetGroup();
      case StatusPackage.GROUP_S__ACHIEVEMENTS:
        return getAchievements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case StatusPackage.GROUP_S__GROUP:
        setGroup((Group)newValue);
        return;
      case StatusPackage.GROUP_S__ACHIEVEMENTS:
        getAchievements().clear();
        getAchievements().addAll((Collection<? extends AchievementS>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case StatusPackage.GROUP_S__GROUP:
        setGroup((Group)null);
        return;
      case StatusPackage.GROUP_S__ACHIEVEMENTS:
        getAchievements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case StatusPackage.GROUP_S__GROUP:
        return group != null;
      case StatusPackage.GROUP_S__ACHIEVEMENTS:
        return achievements != null && !achievements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //GroupSImpl
