/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status.tests

import codeskills.designer.game.status.status.Status
import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(StatusInjectorProvider)
class StatusParsingTest{

	@Inject
	ParseHelper<Status> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
