/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.game;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Group</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.game.game.Group#getAchievements <em>Achievements</em>}</li>
 * </ul>
 *
 * @see codeskills.designer.game.game.GamePackage#getGroup()
 * @model
 * @generated
 */
public interface Group extends Rewardable
{
  /**
   * Returns the value of the '<em><b>Achievements</b></em>' containment reference list.
   * The list contents are of type {@link codeskills.designer.game.game.Achievement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Achievements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Achievements</em>' containment reference list.
   * @see codeskills.designer.game.game.GamePackage#getGroup_Achievements()
   * @model containment="true"
   * @generated
   */
  EList<Achievement> getAchievements();

} // Group
