/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.game;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Level</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.game.game.Level#getGroups <em>Groups</em>}</li>
 * </ul>
 *
 * @see codeskills.designer.game.game.GamePackage#getLevel()
 * @model
 * @generated
 */
public interface Level extends Rewardable
{
  /**
   * Returns the value of the '<em><b>Groups</b></em>' containment reference list.
   * The list contents are of type {@link codeskills.designer.game.game.Group}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Groups</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Groups</em>' containment reference list.
   * @see codeskills.designer.game.game.GamePackage#getLevel_Groups()
   * @model containment="true"
   * @generated
   */
  EList<Group> getGroups();

} // Level
