/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Notification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.game.game.Notification#getMessage <em>Message</em>}</li>
 *   <li>{@link codeskills.designer.game.game.Notification#getIconPath <em>Icon Path</em>}</li>
 *   <li>{@link codeskills.designer.game.game.Notification#getSoundPath <em>Sound Path</em>}</li>
 * </ul>
 *
 * @see codeskills.designer.game.game.GamePackage#getNotification()
 * @model
 * @generated
 */
public interface Notification extends EObject
{
  /**
   * Returns the value of the '<em><b>Message</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Message</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message</em>' attribute.
   * @see #setMessage(String)
   * @see codeskills.designer.game.game.GamePackage#getNotification_Message()
   * @model
   * @generated
   */
  String getMessage();

  /**
   * Sets the value of the '{@link codeskills.designer.game.game.Notification#getMessage <em>Message</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Message</em>' attribute.
   * @see #getMessage()
   * @generated
   */
  void setMessage(String value);

  /**
   * Returns the value of the '<em><b>Icon Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Icon Path</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Icon Path</em>' attribute.
   * @see #setIconPath(String)
   * @see codeskills.designer.game.game.GamePackage#getNotification_IconPath()
   * @model
   * @generated
   */
  String getIconPath();

  /**
   * Sets the value of the '{@link codeskills.designer.game.game.Notification#getIconPath <em>Icon Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Icon Path</em>' attribute.
   * @see #getIconPath()
   * @generated
   */
  void setIconPath(String value);

  /**
   * Returns the value of the '<em><b>Sound Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sound Path</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sound Path</em>' attribute.
   * @see #setSoundPath(String)
   * @see codeskills.designer.game.game.GamePackage#getNotification_SoundPath()
   * @model
   * @generated
   */
  String getSoundPath();

  /**
   * Sets the value of the '{@link codeskills.designer.game.game.Notification#getSoundPath <em>Sound Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sound Path</em>' attribute.
   * @see #getSoundPath()
   * @generated
   */
  void setSoundPath(String value);

} // Notification
