/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rewardable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.game.game.Rewardable#getName <em>Name</em>}</li>
 *   <li>{@link codeskills.designer.game.game.Rewardable#getDescription <em>Description</em>}</li>
 *   <li>{@link codeskills.designer.game.game.Rewardable#getReward <em>Reward</em>}</li>
 * </ul>
 *
 * @see codeskills.designer.game.game.GamePackage#getRewardable()
 * @model
 * @generated
 */
public interface Rewardable extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see codeskills.designer.game.game.GamePackage#getRewardable_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link codeskills.designer.game.game.Rewardable#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see codeskills.designer.game.game.GamePackage#getRewardable_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link codeskills.designer.game.game.Rewardable#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Reward</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Reward</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reward</em>' containment reference.
   * @see #setReward(Reward)
   * @see codeskills.designer.game.game.GamePackage#getRewardable_Reward()
   * @model containment="true"
   * @generated
   */
  Reward getReward();

  /**
   * Sets the value of the '{@link codeskills.designer.game.game.Rewardable#getReward <em>Reward</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reward</em>' containment reference.
   * @see #getReward()
   * @generated
   */
  void setReward(Reward value);

} // Rewardable
