/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.game;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reward</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.game.game.Reward#getPoints <em>Points</em>}</li>
 *   <li>{@link codeskills.designer.game.game.Reward#getBadgePath <em>Badge Path</em>}</li>
 *   <li>{@link codeskills.designer.game.game.Reward#getNotification <em>Notification</em>}</li>
 * </ul>
 *
 * @see codeskills.designer.game.game.GamePackage#getReward()
 * @model
 * @generated
 */
public interface Reward extends EObject
{
  /**
   * Returns the value of the '<em><b>Points</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Points</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Points</em>' attribute.
   * @see #setPoints(int)
   * @see codeskills.designer.game.game.GamePackage#getReward_Points()
   * @model
   * @generated
   */
  int getPoints();

  /**
   * Sets the value of the '{@link codeskills.designer.game.game.Reward#getPoints <em>Points</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Points</em>' attribute.
   * @see #getPoints()
   * @generated
   */
  void setPoints(int value);

  /**
   * Returns the value of the '<em><b>Badge Path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Badge Path</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Badge Path</em>' attribute.
   * @see #setBadgePath(String)
   * @see codeskills.designer.game.game.GamePackage#getReward_BadgePath()
   * @model
   * @generated
   */
  String getBadgePath();

  /**
   * Sets the value of the '{@link codeskills.designer.game.game.Reward#getBadgePath <em>Badge Path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Badge Path</em>' attribute.
   * @see #getBadgePath()
   * @generated
   */
  void setBadgePath(String value);

  /**
   * Returns the value of the '<em><b>Notification</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Notification</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notification</em>' containment reference.
   * @see #setNotification(Notification)
   * @see codeskills.designer.game.game.GamePackage#getReward_Notification()
   * @model containment="true"
   * @generated
   */
  Notification getNotification();

  /**
   * Sets the value of the '{@link codeskills.designer.game.game.Reward#getNotification <em>Notification</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Notification</em>' containment reference.
   * @see #getNotification()
   * @generated
   */
  void setNotification(Notification value);

} // Reward
