/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGameScopeProvider extends DelegatingScopeProvider {
}
