/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class GameScopeProvider extends AbstractGameScopeProvider {

}
