/*
 * generated by Xtext 2.10.0
 */
package codeskills.designer.data.ui;

import codeskills.designer.data.ui.internal.DataActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DataExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DataActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DataActivator.getInstance().getInjector(DataActivator.CODESKILLS_DESIGNER_DATA_DATA);
	}
	
}
