/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status.status;

import codeskills.designer.game.game.Achievement;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Achievement S</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.game.status.status.AchievementS#getAchievement <em>Achievement</em>}</li>
 *   <li>{@link codeskills.designer.game.status.status.AchievementS#getTasks <em>Tasks</em>}</li>
 * </ul>
 *
 * @see codeskills.designer.game.status.status.StatusPackage#getAchievementS()
 * @model
 * @generated
 */
public interface AchievementS extends S
{
  /**
   * Returns the value of the '<em><b>Achievement</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Achievement</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Achievement</em>' reference.
   * @see #setAchievement(Achievement)
   * @see codeskills.designer.game.status.status.StatusPackage#getAchievementS_Achievement()
   * @model
   * @generated
   */
  Achievement getAchievement();

  /**
   * Sets the value of the '{@link codeskills.designer.game.status.status.AchievementS#getAchievement <em>Achievement</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Achievement</em>' reference.
   * @see #getAchievement()
   * @generated
   */
  void setAchievement(Achievement value);

  /**
   * Returns the value of the '<em><b>Tasks</b></em>' containment reference list.
   * The list contents are of type {@link codeskills.designer.game.status.status.TaskS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tasks</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tasks</em>' containment reference list.
   * @see codeskills.designer.game.status.status.StatusPackage#getAchievementS_Tasks()
   * @model containment="true"
   * @generated
   */
  EList<TaskS> getTasks();

} // AchievementS
