/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status.status;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>S</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.game.status.status.S#getStatus <em>Status</em>}</li>
 * </ul>
 *
 * @see codeskills.designer.game.status.status.StatusPackage#getS()
 * @model
 * @generated
 */
public interface S extends EObject
{
  /**
   * Returns the value of the '<em><b>Status</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Status</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Status</em>' containment reference.
   * @see #setStatus(Status)
   * @see codeskills.designer.game.status.status.StatusPackage#getS_Status()
   * @model containment="true"
   * @generated
   */
  Status getStatus();

  /**
   * Sets the value of the '{@link codeskills.designer.game.status.status.S#getStatus <em>Status</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Status</em>' containment reference.
   * @see #getStatus()
   * @generated
   */
  void setStatus(Status value);

} // S
