/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status.status;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see codeskills.designer.game.status.status.StatusFactory
 * @model kind="package"
 * @generated
 */
public interface StatusPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "status";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.designer.codeskills/game/status/Status";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "status";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StatusPackage eINSTANCE = codeskills.designer.game.status.status.impl.StatusPackageImpl.init();

  /**
   * The meta object id for the '{@link codeskills.designer.game.status.status.impl.SImpl <em>S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see codeskills.designer.game.status.status.impl.SImpl
   * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getS()
   * @generated
   */
  int S = 0;

  /**
   * The feature id for the '<em><b>Status</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S__STATUS = 0;

  /**
   * The number of structural features of the '<em>S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link codeskills.designer.game.status.status.impl.GameSImpl <em>Game S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see codeskills.designer.game.status.status.impl.GameSImpl
   * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getGameS()
   * @generated
   */
  int GAME_S = 1;

  /**
   * The feature id for the '<em><b>Status</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_S__STATUS = S__STATUS;

  /**
   * The feature id for the '<em><b>Levels</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_S__LEVELS = S_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Signature</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_S__SIGNATURE = S_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Created</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_S__CREATED = S_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Current Score</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_S__CURRENT_SCORE = S_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Game S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_S_FEATURE_COUNT = S_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link codeskills.designer.game.status.status.impl.LevelSImpl <em>Level S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see codeskills.designer.game.status.status.impl.LevelSImpl
   * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getLevelS()
   * @generated
   */
  int LEVEL_S = 2;

  /**
   * The feature id for the '<em><b>Status</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_S__STATUS = S__STATUS;

  /**
   * The feature id for the '<em><b>Level</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_S__LEVEL = S_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Is Current</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_S__IS_CURRENT = S_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Groups</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_S__GROUPS = S_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Level S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_S_FEATURE_COUNT = S_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link codeskills.designer.game.status.status.impl.GroupSImpl <em>Group S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see codeskills.designer.game.status.status.impl.GroupSImpl
   * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getGroupS()
   * @generated
   */
  int GROUP_S = 3;

  /**
   * The feature id for the '<em><b>Status</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_S__STATUS = S__STATUS;

  /**
   * The feature id for the '<em><b>Group</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_S__GROUP = S_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Achievements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_S__ACHIEVEMENTS = S_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Group S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GROUP_S_FEATURE_COUNT = S_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link codeskills.designer.game.status.status.impl.AchievementSImpl <em>Achievement S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see codeskills.designer.game.status.status.impl.AchievementSImpl
   * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getAchievementS()
   * @generated
   */
  int ACHIEVEMENT_S = 4;

  /**
   * The feature id for the '<em><b>Status</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACHIEVEMENT_S__STATUS = S__STATUS;

  /**
   * The feature id for the '<em><b>Achievement</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACHIEVEMENT_S__ACHIEVEMENT = S_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Tasks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACHIEVEMENT_S__TASKS = S_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Achievement S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACHIEVEMENT_S_FEATURE_COUNT = S_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link codeskills.designer.game.status.status.impl.TaskSImpl <em>Task S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see codeskills.designer.game.status.status.impl.TaskSImpl
   * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getTaskS()
   * @generated
   */
  int TASK_S = 5;

  /**
   * The feature id for the '<em><b>Status</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_S__STATUS = S__STATUS;

  /**
   * The feature id for the '<em><b>Task</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_S__TASK = S_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Task S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TASK_S_FEATURE_COUNT = S_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link codeskills.designer.game.status.status.impl.StatusImpl <em>Status</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see codeskills.designer.game.status.status.impl.StatusImpl
   * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getStatus()
   * @generated
   */
  int STATUS = 6;

  /**
   * The feature id for the '<em><b>Complete</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATUS__COMPLETE = 0;

  /**
   * The feature id for the '<em><b>Milliseconds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATUS__MILLISECONDS = 1;

  /**
   * The number of structural features of the '<em>Status</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATUS_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link codeskills.designer.game.status.status.S <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>S</em>'.
   * @see codeskills.designer.game.status.status.S
   * @generated
   */
  EClass getS();

  /**
   * Returns the meta object for the containment reference '{@link codeskills.designer.game.status.status.S#getStatus <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Status</em>'.
   * @see codeskills.designer.game.status.status.S#getStatus()
   * @see #getS()
   * @generated
   */
  EReference getS_Status();

  /**
   * Returns the meta object for class '{@link codeskills.designer.game.status.status.GameS <em>Game S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game S</em>'.
   * @see codeskills.designer.game.status.status.GameS
   * @generated
   */
  EClass getGameS();

  /**
   * Returns the meta object for the containment reference list '{@link codeskills.designer.game.status.status.GameS#getLevels <em>Levels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Levels</em>'.
   * @see codeskills.designer.game.status.status.GameS#getLevels()
   * @see #getGameS()
   * @generated
   */
  EReference getGameS_Levels();

  /**
   * Returns the meta object for the attribute '{@link codeskills.designer.game.status.status.GameS#getSignature <em>Signature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Signature</em>'.
   * @see codeskills.designer.game.status.status.GameS#getSignature()
   * @see #getGameS()
   * @generated
   */
  EAttribute getGameS_Signature();

  /**
   * Returns the meta object for the attribute '{@link codeskills.designer.game.status.status.GameS#getCreated <em>Created</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Created</em>'.
   * @see codeskills.designer.game.status.status.GameS#getCreated()
   * @see #getGameS()
   * @generated
   */
  EAttribute getGameS_Created();

  /**
   * Returns the meta object for the attribute '{@link codeskills.designer.game.status.status.GameS#getCurrentScore <em>Current Score</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Current Score</em>'.
   * @see codeskills.designer.game.status.status.GameS#getCurrentScore()
   * @see #getGameS()
   * @generated
   */
  EAttribute getGameS_CurrentScore();

  /**
   * Returns the meta object for class '{@link codeskills.designer.game.status.status.LevelS <em>Level S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Level S</em>'.
   * @see codeskills.designer.game.status.status.LevelS
   * @generated
   */
  EClass getLevelS();

  /**
   * Returns the meta object for the reference '{@link codeskills.designer.game.status.status.LevelS#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Level</em>'.
   * @see codeskills.designer.game.status.status.LevelS#getLevel()
   * @see #getLevelS()
   * @generated
   */
  EReference getLevelS_Level();

  /**
   * Returns the meta object for the attribute '{@link codeskills.designer.game.status.status.LevelS#isIsCurrent <em>Is Current</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Current</em>'.
   * @see codeskills.designer.game.status.status.LevelS#isIsCurrent()
   * @see #getLevelS()
   * @generated
   */
  EAttribute getLevelS_IsCurrent();

  /**
   * Returns the meta object for the containment reference list '{@link codeskills.designer.game.status.status.LevelS#getGroups <em>Groups</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Groups</em>'.
   * @see codeskills.designer.game.status.status.LevelS#getGroups()
   * @see #getLevelS()
   * @generated
   */
  EReference getLevelS_Groups();

  /**
   * Returns the meta object for class '{@link codeskills.designer.game.status.status.GroupS <em>Group S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Group S</em>'.
   * @see codeskills.designer.game.status.status.GroupS
   * @generated
   */
  EClass getGroupS();

  /**
   * Returns the meta object for the reference '{@link codeskills.designer.game.status.status.GroupS#getGroup <em>Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Group</em>'.
   * @see codeskills.designer.game.status.status.GroupS#getGroup()
   * @see #getGroupS()
   * @generated
   */
  EReference getGroupS_Group();

  /**
   * Returns the meta object for the containment reference list '{@link codeskills.designer.game.status.status.GroupS#getAchievements <em>Achievements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Achievements</em>'.
   * @see codeskills.designer.game.status.status.GroupS#getAchievements()
   * @see #getGroupS()
   * @generated
   */
  EReference getGroupS_Achievements();

  /**
   * Returns the meta object for class '{@link codeskills.designer.game.status.status.AchievementS <em>Achievement S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Achievement S</em>'.
   * @see codeskills.designer.game.status.status.AchievementS
   * @generated
   */
  EClass getAchievementS();

  /**
   * Returns the meta object for the reference '{@link codeskills.designer.game.status.status.AchievementS#getAchievement <em>Achievement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Achievement</em>'.
   * @see codeskills.designer.game.status.status.AchievementS#getAchievement()
   * @see #getAchievementS()
   * @generated
   */
  EReference getAchievementS_Achievement();

  /**
   * Returns the meta object for the containment reference list '{@link codeskills.designer.game.status.status.AchievementS#getTasks <em>Tasks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tasks</em>'.
   * @see codeskills.designer.game.status.status.AchievementS#getTasks()
   * @see #getAchievementS()
   * @generated
   */
  EReference getAchievementS_Tasks();

  /**
   * Returns the meta object for class '{@link codeskills.designer.game.status.status.TaskS <em>Task S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Task S</em>'.
   * @see codeskills.designer.game.status.status.TaskS
   * @generated
   */
  EClass getTaskS();

  /**
   * Returns the meta object for the reference '{@link codeskills.designer.game.status.status.TaskS#getTask <em>Task</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Task</em>'.
   * @see codeskills.designer.game.status.status.TaskS#getTask()
   * @see #getTaskS()
   * @generated
   */
  EReference getTaskS_Task();

  /**
   * Returns the meta object for class '{@link codeskills.designer.game.status.status.Status <em>Status</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Status</em>'.
   * @see codeskills.designer.game.status.status.Status
   * @generated
   */
  EClass getStatus();

  /**
   * Returns the meta object for the attribute '{@link codeskills.designer.game.status.status.Status#isComplete <em>Complete</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Complete</em>'.
   * @see codeskills.designer.game.status.status.Status#isComplete()
   * @see #getStatus()
   * @generated
   */
  EAttribute getStatus_Complete();

  /**
   * Returns the meta object for the attribute '{@link codeskills.designer.game.status.status.Status#getMilliseconds <em>Milliseconds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Milliseconds</em>'.
   * @see codeskills.designer.game.status.status.Status#getMilliseconds()
   * @see #getStatus()
   * @generated
   */
  EAttribute getStatus_Milliseconds();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  StatusFactory getStatusFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link codeskills.designer.game.status.status.impl.SImpl <em>S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see codeskills.designer.game.status.status.impl.SImpl
     * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getS()
     * @generated
     */
    EClass S = eINSTANCE.getS();

    /**
     * The meta object literal for the '<em><b>Status</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference S__STATUS = eINSTANCE.getS_Status();

    /**
     * The meta object literal for the '{@link codeskills.designer.game.status.status.impl.GameSImpl <em>Game S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see codeskills.designer.game.status.status.impl.GameSImpl
     * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getGameS()
     * @generated
     */
    EClass GAME_S = eINSTANCE.getGameS();

    /**
     * The meta object literal for the '<em><b>Levels</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_S__LEVELS = eINSTANCE.getGameS_Levels();

    /**
     * The meta object literal for the '<em><b>Signature</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_S__SIGNATURE = eINSTANCE.getGameS_Signature();

    /**
     * The meta object literal for the '<em><b>Created</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_S__CREATED = eINSTANCE.getGameS_Created();

    /**
     * The meta object literal for the '<em><b>Current Score</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_S__CURRENT_SCORE = eINSTANCE.getGameS_CurrentScore();

    /**
     * The meta object literal for the '{@link codeskills.designer.game.status.status.impl.LevelSImpl <em>Level S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see codeskills.designer.game.status.status.impl.LevelSImpl
     * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getLevelS()
     * @generated
     */
    EClass LEVEL_S = eINSTANCE.getLevelS();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEVEL_S__LEVEL = eINSTANCE.getLevelS_Level();

    /**
     * The meta object literal for the '<em><b>Is Current</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEVEL_S__IS_CURRENT = eINSTANCE.getLevelS_IsCurrent();

    /**
     * The meta object literal for the '<em><b>Groups</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEVEL_S__GROUPS = eINSTANCE.getLevelS_Groups();

    /**
     * The meta object literal for the '{@link codeskills.designer.game.status.status.impl.GroupSImpl <em>Group S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see codeskills.designer.game.status.status.impl.GroupSImpl
     * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getGroupS()
     * @generated
     */
    EClass GROUP_S = eINSTANCE.getGroupS();

    /**
     * The meta object literal for the '<em><b>Group</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP_S__GROUP = eINSTANCE.getGroupS_Group();

    /**
     * The meta object literal for the '<em><b>Achievements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GROUP_S__ACHIEVEMENTS = eINSTANCE.getGroupS_Achievements();

    /**
     * The meta object literal for the '{@link codeskills.designer.game.status.status.impl.AchievementSImpl <em>Achievement S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see codeskills.designer.game.status.status.impl.AchievementSImpl
     * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getAchievementS()
     * @generated
     */
    EClass ACHIEVEMENT_S = eINSTANCE.getAchievementS();

    /**
     * The meta object literal for the '<em><b>Achievement</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACHIEVEMENT_S__ACHIEVEMENT = eINSTANCE.getAchievementS_Achievement();

    /**
     * The meta object literal for the '<em><b>Tasks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACHIEVEMENT_S__TASKS = eINSTANCE.getAchievementS_Tasks();

    /**
     * The meta object literal for the '{@link codeskills.designer.game.status.status.impl.TaskSImpl <em>Task S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see codeskills.designer.game.status.status.impl.TaskSImpl
     * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getTaskS()
     * @generated
     */
    EClass TASK_S = eINSTANCE.getTaskS();

    /**
     * The meta object literal for the '<em><b>Task</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TASK_S__TASK = eINSTANCE.getTaskS_Task();

    /**
     * The meta object literal for the '{@link codeskills.designer.game.status.status.impl.StatusImpl <em>Status</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see codeskills.designer.game.status.status.impl.StatusImpl
     * @see codeskills.designer.game.status.status.impl.StatusPackageImpl#getStatus()
     * @generated
     */
    EClass STATUS = eINSTANCE.getStatus();

    /**
     * The meta object literal for the '<em><b>Complete</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATUS__COMPLETE = eINSTANCE.getStatus_Complete();

    /**
     * The meta object literal for the '<em><b>Milliseconds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATUS__MILLISECONDS = eINSTANCE.getStatus_Milliseconds();

  }

} //StatusPackage
