/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status.status;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see codeskills.designer.game.status.status.StatusPackage
 * @generated
 */
public interface StatusFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StatusFactory eINSTANCE = codeskills.designer.game.status.status.impl.StatusFactoryImpl.init();

  /**
   * Returns a new object of class '<em>S</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>S</em>'.
   * @generated
   */
  S createS();

  /**
   * Returns a new object of class '<em>Game S</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Game S</em>'.
   * @generated
   */
  GameS createGameS();

  /**
   * Returns a new object of class '<em>Level S</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Level S</em>'.
   * @generated
   */
  LevelS createLevelS();

  /**
   * Returns a new object of class '<em>Group S</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Group S</em>'.
   * @generated
   */
  GroupS createGroupS();

  /**
   * Returns a new object of class '<em>Achievement S</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Achievement S</em>'.
   * @generated
   */
  AchievementS createAchievementS();

  /**
   * Returns a new object of class '<em>Task S</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Task S</em>'.
   * @generated
   */
  TaskS createTaskS();

  /**
   * Returns a new object of class '<em>Status</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Status</em>'.
   * @generated
   */
  Status createStatus();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  StatusPackage getStatusPackage();

} //StatusFactory
