/**
 * generated by Xtext 2.10.0
 */
package codeskills.designer.game.status.status;

import codeskills.designer.game.game.Task;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Task S</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link codeskills.designer.game.status.status.TaskS#getTask <em>Task</em>}</li>
 * </ul>
 *
 * @see codeskills.designer.game.status.status.StatusPackage#getTaskS()
 * @model
 * @generated
 */
public interface TaskS extends S
{
  /**
   * Returns the value of the '<em><b>Task</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Task</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Task</em>' reference.
   * @see #setTask(Task)
   * @see codeskills.designer.game.status.status.StatusPackage#getTaskS_Task()
   * @model
   * @generated
   */
  Task getTask();

  /**
   * Sets the value of the '{@link codeskills.designer.game.status.status.TaskS#getTask <em>Task</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Task</em>' reference.
   * @see #getTask()
   * @generated
   */
  void setTask(Task value);

} // TaskS
